### ISSUE TITLE
Is G equivalent to L in the code?

### ISSUE THREAD

**Issue by r-j-arnold** [SJaffa/Q_plus#1]
Hi Sarah,

It's Becky Arnold, we've met a couple of times at conferences, I did my PhD at Sheffield with Simon Goodwin, I'm at Keele now. I'm looking at applying Q+ to compare some simulations and real clusters and I'm confused because your paper talks about the L parameter, put the code outputs a parameter called G (in addition to D and C). 

Is G just another name for L, or is it something different?

Thanks,

Becky

**Comment by SJaffa** [comment]
Hi Becky, thanks for raising this. Yes, G in the code is what we call L in the outputs and paper.

Sorry for the confusion. When developing this work we called it G (for generation) and then decided on a change of terminology before publication. One day I hope to go back and clean up this code so it is more user friendly and optimise it a bit as I've learned a lot about coding since writing this! Please do let me know if you spot any bugs or ways to optimise!

**Comment by r-j-arnold** [comment]
Hi Sarah, 

That makes sense. I agree L works better for publication as it's more neutrally applicable to simulated and real star forming regions. Thanks very much for clarifying this for me. I'll certainly get back to you if I think of any optimisations, but I'm mostly just using it rather than going into the nuts and bolts so that's not very likely. 

All the best,

Becky
